### PR TITLE
Scroll interactivity docs examples

### PR DESCRIPTION
**Pull request by shelooks16**
Hi. Here is an update for docs examples.

[This is the official lottie guide on interactivity](https://lottiefiles.com/interactivity). It requires installing an additional library and it does not have any context of usage with React. 
Pushed changes show how to achieve the same result with lottie-react and without installing the additional library :yum:

### CODE REVIEW

**Comment by Gamote** [comment]
@shelooks16 Interesting idea, thank you!

I've just pushed the **v2.0.0** release, can you please solve the conflicts so I can give it a look?

**Comment by shelooks16** [comment]
@Gamote Updated. It was just spaces thing :)

**Comment by shelooks16** [comment]
Let me also adjust it to **v2.0.0** since ref was renamed to lottieRef

**Comment by shelooks16** [comment]
Added new commit to match v2.0.0

**Comment by Gamote** [comment]
@shelooks16 Perfect, I will check it soon.

I took a brief look and I wanted to ask before, if it will make sense to integrate it as functionality (part of the library), not just as a method?

**Comment by shelooks16** [comment]
@Gamote I also thought about that! Given functionality can be definetely extended to make it more customizable. I'd like to submit a PR when I have spare time :)

**Comment by Gamote** [comment]
@shelooks16 Sounds good. I will set this PR as draft until then.

**Comment by Gamote** [comment]
Added in #9

**Pull request closed without merging**
