### PR TITLE
Add support for react 17

### PR DESCRIPTION
**Pull request by musayann**
Updated the dependencies and made changes to support react 17

### CODE REVIEW

**Comment by Gamote** [comment]
Hey @musayann, thank you for your PR. I will create a new release soon!

**Comment by sk-** [comment]
@Gamote any chance of releasing a new version including this PR?

**Comment by dtsanan** [comment]
> @Gamote any chance of releasing a new version including this PR?

+1

**Comment by RobinGiel** [comment]
@Gamote was there a problem releasing this PR?

**Comment by Gamote** [comment]
Hey @RobinGiel, the package updated in this PR added some security vulnerabilities.
vulnerabilities

In order to publish it I had to make a bit more changes to the library so I decided to focus all my free time on finishing the `v3` as it's long overdue 👀.. You can follow the progress on the `v3` branch. It should be done in few days and I'm glad to say that exciting things are coming.

Meanwhile you can check out @SpeedOfSpin's comment: https://github.com/Gamote/lottie-react/issues/29#issuecomment-1007660237 in order to use this library with React v17.

**Comment by Gamote** [comment]
Hey guys (@musayann @sk- @dtsanan @RobinGiel)

This issue is solved in the new [v2.2.0](https://github.com/Gamote/lottie-react/releases/tag/v2.2.0) version.

**Pull request merged**
